      
# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"
  # Install dependencies in netlify/functions before building
  command = "cd netlify/functions && npm install"

[functions]
  # Ensure Firebase Admin gets included with the function
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

# Optional redirects/headers...

    