      
# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"
  command = "chmod +x build.sh && ./build.sh"

[functions]
  # Let Netlify bundle the dependencies
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

# Optional redirects/headers...

    